### ISSUE TITLE
Prevent indexing of unwanted items

### ISSUE THREAD

**Issue by gremmie** [django-haystack/queued_search#3]
Just a suggestion.

queued_search puts all models in the queue unconditionally. Some of my models implement get_queryset() on the SearchIndex to control which items get indexed. Is there a way that queued_search can either check to see if the item to be queued is in the get_queryset(), or perhaps call some new method on search index to see if the item should be indexed?

Or perhaps I should just subclass QueuedSearchIndex and override the enqueue method and do this myself?

Thanks.

**Comment by gremmie** [comment]
Thinking about this some more, it isn't that easy. :)
There are complications if I change some aspects of a model instance such that it should not be indexed anymore. In that case I should really delete it from the index even though it is an update operation.
This is telling me that perhaps I should not be using QueuedSearchIndex for the models that have these "conditional index" requirements.
So I guess I'm just throwing that out there in case you have any ideas. Otherwise, feel free to close this issue. QueuedSearchIndex works fine for the simple case where you always want to index an instance on an update.

**Comment by toastdriven** [comment]
You pointed out exactly why it wasn't done this way. Not to mention doing things like date filtering can cause erroneous behavior. I'd suggest you extend `QueuedSearchIndex` & implement the behavior you want.

The other way to handle it is to put _everything_ in the index & filter out what shouldn't be there on the way out (either chaining onto the `SearchQuerySet` or excluding another way).

**Comment by gremmie** [comment]
So far I'm having good luck extending `QueuedSearchIndex` to exclude stuff I don't want in the index. I'll just periodically run a `rebuild_index` to remove items that somehow changed to make them non-eligible. This will work for my site. Thanks for the feedback!

**Comment by gregplaysguitar** [comment]
For what it's worth, heres my approach to this issue:

```
def enqueue_save(self, instance, **kwargs):
    """If the item is no longer live, enqueue a delete instead of an update."""
    if self.index_queryset().filter(pk=instance.pk).count():
        return self.enqueue('update', instance)
    else:
        return self.enqueue('delete', instance)
```
